### ISSUE TITLE
EXEC not working (NGINX 1.10.1)

### ISSUE THREAD

**Issue by ThalysonR** [sergey-dryabzhinsky/nginx-rtmp-module#192]
Trying to use exec but it seems it's just ignored. No logs, no nothing.
Not sure, but nginx version seems to have to do with this issue.

**Comment by karlisk** [comment]
I seemed to have a similar issue, I think it was because of a unrecognized syntax that I was trying to use... I also didn't get any error responses or log entries, however, the CPU usage grew noticably (from ~10% to around 45-65%) as the EXEC spawned children processess (as normally intended and per documentation) but my guess is they were stuck in a error loop (I'm guessing this may be happening in your situation too, so be careful not to accidentally overload your NGINX) I managed to fix the problem I was having by changing the command I was trying to run to a simpler version and later modified it to be run with exec as a *.sh script.

**Comment by ThalysonR** [comment]
Found out i had no permission with nginx user, exec working just fine.

**Comment by hblanken** [comment]
user nobody did not work for me. For all: In your /nginx/conf/nginx.conf set: user pi or user nginx
