### ISSUE TITLE
Low latency HLS

### ISSUE THREAD

**Issue by antonioparisi** [sergey-dryabzhinsky/nginx-rtmp-module#215]
Hi guys,

I'm trying to have a less than 5 seconds latency with HLS.
I saw the guys from http://influxis.com/ afferming:
> LOW LATENCY HLS
Live stream real-time HLS and DASH to mobile devices with less than 5 seconds latency.

I'm generating as usual as other many of us do, multiple bitrates HLS qualities using ffmpeg.
But till now I'm getting only a lot of buffering after the first few seconds.

Nginx version: `1.10.2`
Nginx-rtmp version: `master` branch version.
ffmpeg version: `3.2.2`

Input source on the client side:
frame rate: 30 fps
keyframe interval in seconds: 1
video bitrate: 1.5mbps

nginx side:
hls_fragment: 1s
hls_max_fragment: 2s (hls_fragment * 2)
hls_playlist_length: 3s (this one I'm not sure about how needs to be calculated, should be in this case 1s (hls_freament) chunks * 3?)   
GOP/keyint: 30(fps)*2(hls_fragment)/2 = 30

i.e. on generating a 720p:
`.. -c:v libx264 -c:a aac -b:v 1024k -b:a 128k -vf "scale=960:trunc(ow/a/2)*2" -r 30 -vprofile baseline -level 3.0 -tune zerolatency -preset ultrafast -g 30 -keyint_min 30 -f flv rtmp://.../$name_720p`

Has anyone ever been able to get lower than 5s using HLS? Unfortunately +20s of delay are too much. And moving away from HLS to RTMP is not worth it since I'll loose all the scaling features that HLS offers.

@sergey-dryabzhinsky do you have any idea or anyone else in general?

PS: I hope to have included all the informations needed, in case I missed something please let me know and I'll provide it.

**Comment by chriswiggins** [comment]
Bring your hls_fragment down to 1s, and ensure your key frame interval down to 1s as well (keyint same as fps)

This should give you almost as low as 4s latency

Sent from my iPhone

On 6/02/2017, at 1:30 PM, Antonio Parisi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi guys,

I'm trying to have a less than 5 seconds latency with HLS.
I saw the guys from http://influxis.com/ afferming:

LOW LATENCY HLS
Live stream real-time HLS and DASH to mobile devices with less than 5 seconds latency.

I'm generating as usual as other many of us do, multiple bitrates HLS qualities using ffmpeg.
But till now I'm getting only a lot of buffering after the first few seconds.

Nginx version: 1.10.2
Nginx-rtmp version: master branch version.
ffmpeg version: 3.2.2

Input source on the client side:
frame rate: 30 fps
keyframe interval in seconds: 1
video bitrate: 1.5mbps

nginx side:
hls_fragment: 2s
hls_max_fragment: 2s (hls_fragment * 2)
hls_playlist_length: 6s (this one I'm not sure about how needs to be calculated, should be 2s (hls_freament) chunks * 3?)
GOP/keyint: 30(fps)*2(hls_fragment)/2 = 30

i.e. on generating a 720p:
.. -c:v libx264 -c:a aac -b:v 1024k -b:a 128k -vf "scale=960:trunc(ow/a/2)*2" -r 24 -vprofile baseline -level 3.0 -tune zerolatency -preset ultrafast -g 60 -keyint_min 60 -f flv rtmp://.../$name_720p

Has anyone ever been able to get lower than 5s using HLS? Unfortunately 15-20s of delay are too much. And moving away from HLS to RTMP is not worth it since I'll loose all the scaling features that HLS offers.

@sergey-dryabzhinsky<https://github.com/sergey-dryabzhinsky> do you have any idea or anyone else in general?

PS: I hope to have included all the informations needed, in case I missed something please let me know and I'll provide it.

**Comment by antonioparisi** [comment]
@chriswiggins awesome - that's worked like a charm :)

so far I set the `hls_playlist_length` to `3s`. and the result is this:

<img width="747" alt="screen shot 2017-02-06 at 12 30 37" src="https://cloud.githubusercontent.com/assets/1324178/22647287/863cbf54-ec68-11e6-99cf-2cbe8b0c2c44.png">

I saw sometimes it was nearly the limit but never buffered so far.
Also this depends from latency between server + CDN + internet latency.

Do you think I can try to increase a little bit the `hls_playlist_length`, like `4s`?
Give me suggestion please :)

Thanks a lot 👍

**Comment by chriswiggins** [comment]
The `hls_playlist_length` wont affect how big the buffer is, so I recommend you set it to something like `15s` so that if a client does have a bit of buffering it will work fine for them

**Comment by winkmichael** [comment]
https://developer.apple.com/documentation/http_live_streaming/protocol_extension_for_low-latency_hls_preliminary_specification
https://developer.apple.com/videos/play/wwdc2019/502/
