### ISSUE TITLE
Use exec_pull for hls

### ISSUE THREAD

**Issue by Tralapo** [sergey-dryabzhinsky/nginx-rtmp-module#59]
I gave exec_pull a try today and it looks impressive. Making use of that would save a lot of bandwith and processing power that's now used for streams where people are not always looking at.

But, bummer, it does not work with hls... and I'm only using hls at the moment.

Would there be a way to make exec_pull work for hls too? Or is it too complicated?

**Comment by mr-deamon** [comment]
I don't think that would be a good idea. Your (first) viewer would have to
wait for the pull to start and for the first (at least two) segments to be
stored to the disk... The only thing you could do if this could and would
be implemented is to display your first viewer(s) a message asking for
patience...

**Comment by matiaspl** [comment]
I once had an idea of doing it based on a redirecting php script which
would spawn a transcoding wrapper, wait for the hls playlists to show up
and then do a 30x HTTP redirect to it. And then using some sort of session
tracking cookie+javascript+webservice too keep track if the webpage with
the player is still open or not, and if it's the last one so we could kill
the transcoder.

The problem is playing the stream wouldn't work anything close to instant,
and that's what we're all fighting for. Ffmpeg transcoding (or remuxing)
usually takes a couple of seconds just to start, and then a whole GOP has
to pass through nginx-rtmp for the first TS segment to be created. And then
there's the Apple HLS specification which suggests that the playlist for
live streams should be at least 3 segment long. So even if you have single
second segments, it would take I'd say 5-10 seconds to keep the stream up
and running. If it's applicable to your use case feel free to go down this
route.

Matt

2015-12-19 15:58 GMT+01:00 Tralapo <notifications@github.com>:

**Comment by Tralapo** [comment]
Well, yes, you guys are right I guess. Didn't think that through good enough.

Still a waste of bandwith though, these long nights with one or two viewers every few hours.

**Comment by sergey-dryabzhinsky** [comment]
What you are trying to achieve? How you think you can save bandwidth with HLS? Or processor power.

You can't create multiple output streams with different quality settings?
And restream+transcode original stream when someone connects to 'low-bw' application?

Since HLS is processed by http modules you can try to make some workaround with perl or lua bindings.

**Comment by Tralapo** [comment]
No, I don't think I can save bandwith by using HLS, but I am only using HLS for streaming.

I found it was such a shame the server is pulling a stream 24/7 from a source (so wasting pricey bandwith) while almost nobody is watching, especially during the night.

Exec_pull sounded as great solution, because it won't pull (and so create bandwith) when nobody is watching. But, because I'm only using HLS to stream, that won't work.

**Comment by mr-deamon** [comment]
> (...)the server is pulling a stream 24/7 from a source (so wasting pricey
bandwith)

But that would be downstream-traffic, and this is usually free, isn't it?

**Comment by Tralapo** [comment]
For me it's not

**Comment by mr-deamon** [comment]
What about having a permanent rtmp stream at a "free location" and
reverse-proxying the segments on your delivery machine?

**Comment by misiek08** [comment]
I don't belive when someone uses pricey Amazon services, but in case when
someone pays for incoming traffic is even more surprising.
Pull on HLS client needs custom http server or Lua scripting.

**Comment by Tralapo** [comment]
It's not that important, it was just a tought
